apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-content-hash
  labels:
    app: {{ include "sample-app.name" . }}
data:
  contentVersion: "{{ .Values.contentVersion }}"
