apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    app: {{ include "sample-app.name" . }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sample-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sample-app.name" . }}
      annotations:
        checksum/content: "{{ .Values.contentVersion }}"
    spec:
      volumes:
        - name: git-content
          emptyDir: {}
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: git-content
              mountPath: /usr/share/nginx/html
        - name: git-sync
          image: {{ .Values.image.gitSync }}
          volumeMounts:
            - name: git-content
              mountPath: /git
          env:
            - name: GIT_SYNC_REPO
              value: "{{ .Values.gitSync.repo }}"
            - name: GIT_SYNC_BRANCH
              value: "{{ .Values.gitSync.branch }}"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_WAIT
              value: "{{ .Values.gitSync.wait }}"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
